baseURL = "http://example.org/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "loubach"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Learn"
url = "#learn"
weight = 3
[[menu.main]]
name = "Volunteer"
url = "#volunteer"
weight = 4
[[menu.main]]
name = "Locations"
url = "#locations"
weight = 5
[[menu.main]]
name = "Contact Us"
url = "#contact"
weight = 6
#[[menu.main]]
#name = "Resume"
#url = "#resume"
#weight = 5
#[[menu.main]]
#name = "Skills"
#url = "#skills"
#weight = 6
#[[menu.main]]
#name = "Blog"
#url = "#blog"
#weight = 7
#[[menu.main]]
#name = "Contact"
#url = "#contact"
#weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Learn English"
url = "#Learn"
weight = 2
[[menu.sitemap]]
name = "Volunteer to teach english"
url = "#volunteer"
weight = 3
[[menu.sitemap]]
name = "Contact Us"
url = "#contact"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "#contact"
copyright = "All right reserved copyright © [HMV Soluciones](https://hmvsoluciones.com)"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "San Diego"
email = "JQuilkey@mac.com"
openingHours = ""
phone = ""

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
